# Generated by Django 5.1.7 on 2025-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mean_full_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
            ],
        ),
    ]
