# Generated by Django 5.1.7 on 2025-04-17 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aws_ccna_data_analytics_data_science_devops_engineer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('PHP Fullstack', 'PHP Fullstack'), ('Python Fullstack', 'Python Fullstack'), ('Java Fullstack', 'Java Fullstack'), ('C#.NET Core 7 Fullstack', 'C#.NET Core 7 Fullstack'), ('MEAN Fullstack', 'MEAN Fullstack'), ('MERN Fullstack', 'MERN Fullstack'), ('Data Science & AI (Python Guru)', 'Data Science & AI (Python Guru)'), ('Python Mastery (Python / Django / MYSQL)', 'Python Mastery (Python / Django / MYSQL)'), ('Google Flutter Mobile App Development (iOS / Android)', 'Google Flutter Mobile App Development (iOS / Android)'), ('UI/UX Designing', 'UI/UX Designing'), ('Digital Marketing Master Program', 'Digital Marketing Master Program'), ('Software Testing Advanced (Manual / Automation)', 'Software Testing Advanced (Manual / Automation)'), ('Software Testing Manual (ISTQB)', 'Software Testing Manual (ISTQB)'), ('ISTQB CERTIFICATION (EXAM Reg)', 'ISTQB CERTIFICATION (EXAM Reg)'), ('Selenium Testings & Cuccumber / Appium Mobile / QTP / Landrunner / Jmeter / Jira', 'Selenium Testings & Cuccumber / Appium Mobile / QTP / Landrunner / Jmeter / Jira'), ('Computer Networking (CCNA)', 'Computer Networking (CCNA)'), ('Server Admin (MCSE)', 'Server Admin (MCSE)'), ('Server Admin (RHCE)', 'Server Admin (RHCE)'), ('Networking & Server Admin (CCNA / MCSE / Hardware )', 'Networking & Server Admin (CCNA / MCSE / Hardware )'), ('Networking & Server Admin (CCNA / RHCE / Hardware)', 'Networking & Server Admin (CCNA / RHCE / Hardware)'), ('Networking & Server Admin (CCNA / MCSE / RHCE / Hardware)', 'Networking & Server Admin (CCNA / MCSE / RHCE / Hardware)'), ('Security Surveillance & Networking Internship(CCNA / CCTV / Hardware)', 'Security Surveillance & Networking Internship(CCNA / CCTV / Hardware)'), ('Cloud Admin (AWS / MS AZURE)', 'Cloud Admin (AWS / MS AZURE)'), ('Cloud & Networking Admin (CCNA / AWS / Hardware)', 'Cloud & Networking Admin (CCNA / AWS / Hardware)'), ('Cloud & Networking Admin (CCNA / MS ASURE / Hardware)', 'Cloud & Networking Admin (CCNA / MS ASURE / Hardware)'), ('Cloud & Networking Admin (CCNA / AWS)', 'Cloud & Networking Admin (CCNA / AWS)'), ('Cloud & Networking Admin (CCNA / MS AZURE)', 'Cloud & Networking Admin (CCNA / MS AZURE)'), ('Cloud & Server Admin (MCSE / AWS / Hardware)', 'Cloud & Server Admin (MCSE / AWS / Hardware)'), ('Cloud & Server Admin (MCSE / MS AZURE / Hardware)', 'Cloud & Server Admin (MCSE / MS AZURE / Hardware)'), ('Cloud & Server Admin (RHCE / AWS / Hardware)', 'Cloud & Server Admin (RHCE / AWS / Hardware)'), ('Cloud & Server Admin (RHCE / MS AZURE / Hardware)', 'Cloud & Server Admin (RHCE / MS AZURE / Hardware)'), ('Cloud,Networking,Server Admin (CCNA / AWS / AZURE / MCSE / RHCE /Hardware)', 'Cloud,Networking,Server Admin (CCNA / AWS / AZURE / MCSE / RHCE /Hardware)'), ('Devops Mastery (All Together)', 'Devops Mastery (All Together)'), ('Devops-Selective', 'Devops-Selective'), ('Academic Project', 'Academic Project'), ('Ms Office (World / Excel / Power Point / Out Look)', 'Ms Office (World / Excel / Power Point / Out Look)'), ('Data Analytics', 'Data Analytics'), ('Advanced Ms Excel', 'Advanced Ms Excel'), ('Graphic Designing (Photoshop)', 'Graphic Designing (Photoshop)'), ('Graphic Designing  (Photoshop / Illustrator)', 'Graphic Designing  (Photoshop / Illustrator)'), ('None Of The Above , Will Discuss Directly', 'None Of The Above , Will Discuss Directly')], max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('regemail', models.EmailField(max_length=50, unique=True)),
                ('gaurdianmobile', models.CharField(max_length=15)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=100)),
                ('places', models.CharField(choices=[('technopark', 'Technopark'), ('thampanoor', 'Thampanoor'), ('kochi', 'Kochi'), ('nagarcoil', 'Nagarcoil'), ('online', 'Online')], max_length=100)),
                ('gaurdianname', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('time', models.BooleanField(default=False)),
                ('adress', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('hobbies', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
