# Generated by Django 5.1.7 on 2025-04-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_aws_ccna_data_analytics_data_science_devops_engineer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
    ]
