# Generated by Django 5.1.7 on 2025-04-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('course', models.CharField(choices=[('PHP Fullstack', 'PHP Fullstack'), ('Python Fullstack', 'Python Fullstack'), ('Java Fullstack', 'Java Fullstack'), ('C#.NET Core 7 Fullstack', 'C#.NET Core 7 Fullstack'), ('MEAN Fullstack', 'MEAN Fullstack'), ('MERN Fullstack', 'MERN Fullstack'), ('Data Science & AI (Python Guru)', 'Data Science & AI (Python Guru)'), ('Python Mastery (Python / Django / MYSQL)', 'Python Mastery (Python / Django / MYSQL)'), ('Google Flutter Mobile App Development (iOS / Android)', 'Google Flutter Mobile App Development (iOS / Android)'), ('UI/UX Designing', 'UI/UX Designing')], max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('regemail', models.EmailField(max_length=50, unique=True)),
                ('gaurdianmobile', models.CharField(max_length=15)),
                ('mode', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], max_length=100)),
                ('places', models.CharField(choices=[('technopark', 'technopark'), ('thampanoor', 'thampanoor'), ('kochi', 'kochi'), ('nagarcoil', 'nagarcoil'), ('online', 'online')], max_length=100)),
                ('gaurdianname', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('time', models.BooleanField(default=False)),
                ('adress', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=15)),
                ('hobbies', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
