# Generated by Django 5.1.7 on 2025-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_accountdetail_contactmodel_registermodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
