# Generated by Django 5.1.7 on 2025-04-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_registermodel_alter_contactmodel_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registermodel',
            new_name='Registermodels',
        ),
    ]
