# Generated by Django 5.1.7 on 2025-04-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_registermodel_registermodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registermodels',
            new_name='Registermodel',
        ),
    ]
